config/routes.rb
Questions::Application.routes.draw do
  resources :questions

  

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :qlevel, :qtype
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.js
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<meta name="apple-mobile-web-app-status-bar-style" content="black">
	    <meta name="google-site-verification" content="i9Jaxytu5KfWNzdq66rjR-4iZnv5SMHSXHXp6IEKuTM" />
		<link type="text/css" rel="apple-touch-icon-precomposed" href="images/icon.png?v=1" />

	    <script src="js/modernizr-2.5.3.min.js" type="text/javascript"></script>

	     <script type="text/javascript">
			  if (!location.hash)
			  {location.href = location + "#home";}
	 	</script>

	    <script type="text/javascript" src="//use.typekit.net/ejp8few.js"></script>
		<script type="text/javascript">try{Typekit.load();}catch(e){}</script>

	<link rel="stylesheet" type="text/css" href="css/style.css"/>

</head>

<body>
<div class="container">
	
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	 
	<%= yield %>

</div>

<div class= "matrix">
</div>

<div class= "main">

	<div class= "heading">
		<div class= "mt"><top>Questions</top></div>
	</div>

	<div class= "leftmargin">
		<div class="mt"><%= image_tag("logo-mepro.png") %></div>
		<%= button_to "Take me Home", questions_url, method: :index %>
	</div>

</div>

</body>

</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :qtype %><br />
    <%= f.text_area :qtype %>
  </div>
  <div class="field">
    <%= f.label :qlevel %><br />
    <%= f.number_field :qlevel %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/home.html.erb
<div class= "main">
	<div class= "content">
		<div class="bt">
		<%= button_to "Give me a question", questions_url, method: :show %>
		</div>
	</div>
</div>

app/views/questions/index.html.erb
<div class= "main">
	<div class="content">
		<div class= "mt">
			<div class= "ml">
				<table>
			  		<tr>
			    		<th>id</th>
						<th>Qtype</th>
			    		<th>Qlevel</th>
			    		<th></th>
			    		<th></th>
			    		<th></th>
			  		</tr>
					<% @questions.each do |question| %>
			  		<tr>
			    		<td><%= question.id %></td>
						<td><%= question.qtype %></td>
			    		<td><%= question.qlevel %></td>
			    		<td><%= link_to 'Show', question %></td>
			    		<td><%= link_to 'Edit', edit_question_path(question) %></td>
			    		<td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			  		</tr>
					<% end %>
				</table>
				<%= link_to 'New Question', new_question_path %>
			</div>
		</div>
	</div>
</div>

<br />

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Qtype:</b>
  <%= @question.qtype %>
</p>

<p>
  <b>Qlevel:</b>
  <%= @question.qlevel %>
</p>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>